---
apiVersion: v1
kind: Service
metadata:
  name: cribl-stream-standalone-hec
  namespace: monitoring
  labels:
    app: cribl-stream-standalone
spec:
  type: NodePort
  selector:
    app: cribl-stream-standalone
  ports:
    - name: edge-hec
      port: 8088
      targetPort: 8088
      nodePort: 30088
      protocol: TCP
