apiVersion: v1
kind: Service
metadata:
  name: bifrost
  namespace: monitoring
  labels:
    app: bifrost
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: bifrost
  ports:
    - name: api
      port: 8080
      targetPort: 8080
      protocol: TCP
