apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - statefulset.yaml
  - service.yaml
  - service-ui.yaml
  - pdb.yaml

configMapGenerator:
  - name: cribl-edge-standalone-config
    namespace: monitoring
    options:
      disableNameSuffixHash: true
    files:
      - install-packs.sh=scripts/install-packs.sh
      - outputs.yml=outputs.yml
      - limits.yml=limits.yml
