outputs:
  stream-hec:
    type: splunk_hec
    url: "http://cribl-stream-standalone:8088/services/collector"
    token: "edge-internal"
    index: claude
    source: cribl-edge-standalone
    rejectUnauthorized: false
    compress: false
    concurrency: 5
    maxPayloadSizeKB: 4096
    onBackpressure: block
    pqEnabled: true
    pqMaxSize: "5GB"
    pqPath: /opt/cribl/data/pq
  default:
    type: default
    defaultId: stream-hec
