apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - statefulset.yaml
  - service.yaml
  - service-ui.yaml
  - configmap-cribl-config.yaml
  - pdb.yaml

configMapGenerator:
  - name: cribl-stream-standalone-config
    namespace: monitoring
    options:
      disableNameSuffixHash: true
    files:
      - install-packs.sh=scripts/install-packs.sh
    behavior: merge
